site_name: Disnake Guide
site_description: A guide for disnake.
site_url: https://guide.disnake.dev/

theme:

    name: material
    logo: assets/disnake-logo.png
    favicon: assets/disnake-logo.png

    custom_dir: docs/overrides

    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - toc.integrate
        - content.tabs.link

    language: en

    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: light
          toggle: 
            icon: material/weather-sunny
            name: Light Mode
        - media: "(prefers-color-scheme: dark)"
          scheme: dark
          toggle:
            icon: material/weather-night
            name: Dark Mode

repo_name: DisnakeDev/disnake
repo_url: https://github.com/DisnakeDev/disnake
edit_uri: ""

plugins:

    - search
    - macros

    - git-revision-date-localized:
        type: date

extra: {
    guiderepo: https://github.com/DisnakeDev/guide,
    disnakedocs: https://docs.disnake.dev/en/latest,
    disnakeserver: https://discord.gg/gJDbCw8aQy,
    dpydocs: https://discordpy.readthedocs.io/en/latest,
    dpyserver: https://discord.gg/dpy,
    discord: https://www.discord.com,
    devportal: https://discord.com/developers/applications,
    devdocs: https://discord.com/developers/docs,
    discordsupport: https://support.discord.com/hc/en-us,
    breakingchanges: https://gist.github.com/apple502j/f75b4f24652f04de85c7084ffd73ec58,
    futureofdpy: https://gist.github.com/Rapptz/4a2f62751b9600a31a0d3c78100287f1
}

markdown_extensions:

    - tables
    - admonition
    - attr_list

    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.snippets
    - pymdownx.details

    - markdown_link_attr_modifier:
        new_tab: external_only

    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

    - toc:
        permalink: True

nav:

    - index.md
    - links-credits.md
    - migrating-from-dpy.md

    - Prerequisites:
        - 000-prerequisites/001-installing-python.md
        - 000-prerequisites/002-creating-your-application.md
        - 000-prerequisites/003-inviting-your-bot.md

    - Getting Started:
        - 100-getting-started/101-initial-files.md
        - 100-getting-started/102-creating-commands.md
        - 100-getting-started/103-command-handling.md
        - 100-getting-started/104-event-handling.md

    - Interactions:
        - 200-interactions/201-interactions.md
        - 200-interactions/202-application-commands.md
        - 200-interactions/203-message-components.md
        
    - Popular Topics:
        - 300-popular-topics/301-threads.md
        - 300-popular-topics/302-embeds.md
        - 300-popular-topics/303-reactions.md
        - 300-popular-topics/304-webhooks.md
        - 300-popular-topics/305-permissions.md
        - 300-popular-topics/306-intents.md
    
    - Frequently Asked Questions:
        - 400-faq/401-good-practices.md

extra_css:
    - stylesheets/lightmode.css
    - stylesheets/darkmode.css